title: Natali Vilatuña - Ingeniera en Mecatrónica
description: Portafolio profesional de Natali Vilatuña, especializada en automatización, robótica y sistemas embebidos.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
